# Generated by Django 4.2.7 on 2023-11-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
